# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ROBOT_TESTS_DIR: 'Tests'
  ROBOT_REPORTS_DIR: 'Results'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
  displayName: 'Install dependencies'

- script: |
    echo "Installing Chrome"
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
    echo "Installed Chrome version:"
    google-chrome --version
    CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
    echo "##vso[task.setvariable variable=CHROME_VERSION]$CHROME_VERSION"
  displayName: 'Install Chrome'

- script: |
    echo "Installing ChromeDriver"
    sudo apt-get update
    sudo apt-get install -y wget unzip
    wget -N https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip
    unzip chromedriver-linux64.zip
    sudo mv -f chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
    sudo chown root:root /usr/local/bin/chromedriver
    sudo chmod 0755 /usr/local/bin/chromedriver
    echo "Installed ChromeDriver version:"
    /usr/local/bin/chromedriver --version
  displayName: 'Install ChromeDriver'
  

- script: |
    echo "Current directory:"
    pwd
    echo "Listing root directory contents:"
    ls -la
    echo "Listing Tests directory contents:"
    ls -la $(ROBOT_TESTS_DIR)
    robot -d $(ROBOT_REPORTS_DIR) $(ROBOT_TESTS_DIR)
  displayName: 'Run Robot Framework tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(ROBOT_REPORTS_DIR)'
    artifactName: 'TestResults'
  displayName: 'Publish Test Results'


